### PR TITLE
Fix: Uncaught Error: Cannot unset readonly property Pheanstalk\Socket\SocketSocket::$socket in SocketSocket.php on line 138

### PR DESCRIPTION
**Pull request by AnnaDamm**
Reproduction:

```php
<?php
use Pheanstalk\Connection;

$connection = new Connection(new SocketFactory('localhost'));
$connection->connect();
$connection->disconnect();
```

### CODE REVIEW

**Review by pascalheidmann — APPROVED** [review]

**Comment by AnnaDamm** [comment]
Hey @SamMousa, could you have a look at this PR please?

**Comment by SamMousa** [comment]
Yes! Apologies for not getting to this, I totally missed it.

Looks good, except the introduction of a new abstract class.
They should be avoided whenever possible, in this case by introducing a
trait. There already is a trait called `BugfixConnectiomlnTests`.

You may use that one or introduce a new trait for these tests.

Alternatively just add the test to the base since it should have been there
anyway.

I'll look from pc tomorrow, so take these notes as draft only please 🙏

**Comment by AnnaDamm** [comment]
@SamMousa I changed the abstract class to be a trait. I am not using the existing trait, because that is used in the base test. but my test only works with connections that are created with the Connection class.

**Review by SamMousa — APPROVED** [review]
Thanks!

**Pull request merged**
